#Dockerfile for the server that hosts iCal files.
FROM python:3.10-slim-buster
WORKDIR /app
#Install requriements
COPY requirements.txt requirements.txt
RUN pip install -r "requirements.txt"
#Copy other files
COPY . .
#Expose and run server
EXPOSE 5000
CMD ["gunicorn", "--workers",  "2", "--bind", "0.0.0.0:5000", "server:create_app()"]